### ISSUE TITLE
Connect button broken DeviceConnect.js:31

### ISSUE THREAD

**Issue by jcklerk** [dcaputo-harmoni/open-balena-admin#20]
When i try to connect to ssh or VNC using open-balena-admin i get the vollowing error in the javascript console.

Chrome:

DeviceConnect.js:31
```
Uncaught TypeError: Cannot read properties of undefined (reading 'generateKey')
    at genRsaKeys (DeviceConnect.js:31:37)
    at handleSubmit (DeviceConnect.js:75:9)
    at Object.submit (final-form.es.js:1437:1)
    at handleSubmit (react-final-form.es.js:268:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:1)
    at executeDispatch (react-dom.development.js:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:1)
```

Firefox:

DeviceConnect.js:31:8
```
Uncaught TypeError: window.crypto.subtle is undefined
```

**Comment by jcklerk** [comment]
After running the admin, remote and posgrest behind nginxproxy i can connect but get now get the 
Error: 
Unable to connect to device.
this is with both ssh and vnc.

in the vnc log on the client i get the following:
```
[2023-05-15T07:15:45.158Z] 15/05/2023 07:15:45 Got connection from client 10.2.0.1
[2023-05-15T07:15:45.160Z] 15/05/2023 07:15:45 0 other clients
[2023-05-15T07:15:45.160Z] 15/05/2023 07:15:45 webSocketsHandshake: unknown connection error
[2023-05-15T07:15:45.160Z] 15/05/2023 07:15:45 Client 10.2.0.1 gone
[2023-05-15T07:15:45.164Z] 15/05/2023 07:15:45 Statistics events Transmit/ RawEquiv ( saved)
[2023-05-15T07:15:45.165Z] 15/05/2023 07:15:45 TOTALS : 0 | 0/ 0 ( 0.0%)
[2023-05-15T07:15:45.166Z] 15/05/2023 07:15:45 Statistics events Received/ RawEquiv ( saved)
[2023-05-15T07:15:45.166Z] 15/05/2023 07:15:45 TOTALS : 0 | 0/ 0 ( 0.0%)
```

**Comment by jcklerk** [comment]
After running all openbalena-admin web servers behind a ssl proxy the problem was solved
